name: Actions WF

on: [push, pull_request]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: ls files
        run: |
          pwd
          ls -lrta
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo ${{github.token}}
      - name: checkout repo
        uses: actions/checkout@main
      - name: ls files after
        run: |
          pwd
          ls -lrta
      - name: simple js action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: John Wick
      - name: log greet time
        run: echo "${{ steps.greet.outputs.time }}"