name: Actions WF

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: ls files
        run: |
          ls -lrta
      - name: simple js action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: John Wick
      - name: log greet time
        run: echo "${{ steps.greet.outputs.time }}"