name: Shell Commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multi line script
        run: |
          node -v
          npm -v
          echo "my name is kid rock"
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  runs-windows-commands:
    runs-on: windows-latest
    needs: [run-shell-commands]
    steps:
      - name: dir powershell
        run: Get-Location
      - name: dir bash
        run: pwd
        shell: bash